# Generated by Django 5.2.5 on 2025-10-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='demo',
            field=models.CharField(default='demo', max_length=50),
        ),
    ]
